
import java.util.ArrayList;
import static org.junit.Assert.assertTrue;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ay
 */
public class JourneyTestUtils {

    /**
     * Compare all the vertices, if 2 vertices are same, compareTo returns 0
     *
     * @param vertices1 vertices created for the test
     * @param vertices2 vertices generated by the graph
     * @param index
     */
    public static void testVertices(ArrayList<Vertex> vertices1, ArrayList<Vertex> vertices2, int index) {
        // vertex 3 is now placed on index 1, why??
            assertTrue(vertices1.equals(vertices2));
    }

    /**
     * Compare all the edges, if 2 edges are same, compareTo returns 0
     *
     * @param edges1 list 1
     * @param edges2 list 2
     * @param index
     */
    public static void testEdges(ArrayList<Edge> edges1, ArrayList<Edge> edges2, int index) {
        if (index < edges1.size() && index < edges2.size()) {
            assertTrue(edges1.get(index).compareTo(edges2.get(index)) == 0);
            testEdges(edges1, edges2, index + 1);
        }
    }

    /**
     * Compare all the paths
     *
     * @param paths1 list 1
     * @param paths2 list 2
     * @param index
     */
    public static void testPaths(ArrayList<Path> paths1, ArrayList<Path> paths2, int index) {
        if (index < paths1.size() && index < paths2.size()) {
            assertTrue(paths1.get(index).compareTo(paths2.get(index)) == 0);
            testPaths(paths1, paths2, index + 1);
        }
    }
}
